spring.application.name=eventHive

spring.datasource.url=jdbc:postgresql://localhost:5433/event_hive
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
logging.level.org.springframework.security=DEBUG

jwt.secret=sdjkf285252402482374y242r287483762390958qwr238423ioweofhw273hfw093urwhr2832
jwt.expiration=86400000